// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YJuWNEpJbD_pmoJ31EZJ8HJ32dalV1w',
    appId: '1:388941372461:web:1afa87e937c2b8daac6ca4',
    messagingSenderId: '388941372461',
    projectId: 'transmeet-a1f3b',
    authDomain: 'transmeet-a1f3b.firebaseapp.com',
    storageBucket: 'transmeet-a1f3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdguaPF6ARQmPPqEDd3bdOTy5l-0d2Ho',
    appId: '1:388941372461:android:08dce7dbdb6ac2d4ac6ca4',
    messagingSenderId: '388941372461',
    projectId: 'transmeet-a1f3b',
    storageBucket: 'transmeet-a1f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHJpzSLWkf9lH8iO9auMEuRDH_bJd5EU',
    appId: '1:388941372461:ios:c2cce5b3e8e4edc9ac6ca4',
    messagingSenderId: '388941372461',
    projectId: 'transmeet-a1f3b',
    storageBucket: 'transmeet-a1f3b.firebasestorage.app',
    iosBundleId: 'com.example.transmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHJpzSLWkf9lH8iO9auMEuRDH_bJd5EU',
    appId: '1:388941372461:ios:c2cce5b3e8e4edc9ac6ca4',
    messagingSenderId: '388941372461',
    projectId: 'transmeet-a1f3b',
    storageBucket: 'transmeet-a1f3b.firebasestorage.app',
    iosBundleId: 'com.example.transmeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YJuWNEpJbD_pmoJ31EZJ8HJ32dalV1w',
    appId: '1:388941372461:web:11e13cc979c030caac6ca4',
    messagingSenderId: '388941372461',
    projectId: 'transmeet-a1f3b',
    authDomain: 'transmeet-a1f3b.firebaseapp.com',
    storageBucket: 'transmeet-a1f3b.firebasestorage.app',
  );
}
